### ISSUE TITLE
Compiler FormatException: Expected token, but got "null"

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#1033]
As @matanlurey suggested, I've started converting the Angular Tour-of-Heroes example apps so that they are purely static.

The source I'm using is under `examples/ng/doc/toh-0` in this PR https://github.com/dart-lang/site-webdev/pull/1380.

I've successfully converted the app (it builds and runs fine, when not compiling the test files).

But I get the following error when I attempt to build and run tests:

```console
toh-0 > pub run build_runner test --fail-on-severe --delete-conflicting-outputs --output=build -- -p chrome --reporter=expanded
[INFO] Entrypoint: Generating build script completed, took 226ms
[INFO] BuildDefinition: Reading cached asset graph completed, took 262ms
[INFO] BuildDefinition: Checking for updates since last build completed, took 395ms
[SEVERE] Generating .template.dart: Instance of 'Compiler' on angular_tour_of_heroes|test/app_test.dart: Unhandled exception in the AngularDart compiler!

Please report a bug: https://github.com/dart-lang/angular/issues/new
FormatException: Expected token, but got "null".
#0      TokenReader.parseTokenObject (package:angular_compiler/src/analyzer/di/tokens.dart:32:7)
#1      ProviderReader._parseProvider (package:angular_compiler/src/analyzer/di/providers.dart:50:32)
#2      ProviderReader.parseProvider (package:angular_compiler/src/analyzer/di/providers.dart:45:12)
#3      MappedIterator.moveNext (dart:_internal/iterable.dart:392)
#4      new List.from (dart:core-patch/dart:core/array_patch.dart:58)
#5      Iterable.toList (dart:core/iterable.dart:413)
#6      ModuleReader._parseList (package:angular_compiler/src/analyzer/di/modules.dart:66:10)
#7      ModuleReader.parseModule (package:angular_compiler/src/analyzer/di/modules.dart:50:14)
#8      InjectorReader.providers (package:angular_compiler/src/analyzer/di/injector.dart:78:35)
#9      InjectorReader.accept (package:angular_compiler/src/analyzer/di/injector.dart:192:28)
#10     buildGeneratedCode (package:angular/src/source_gen/template_compiler/code_builder.dart:70:16)
#11     generate.<anonymous closure> (package:angular/src/source_gen/template_compiler/generator.dart:25:12)
#12     _rootRunUnary (dart:async/zone.dart:1134)
...
```

Config:

* Dart SDK Version: 2.0.0-dev.32.0 (Thu Mar 1 18:39:53 2018 +0100) on "macos_x64"
* AngularDart Version: `5.0.0-alpha+6`
* OS: macOS

---

**Edit:** here is the `app_test.dart` source for convenience:

```dart
@TestOn('browser')

import 'package:angular/angular.dart';
import 'package:angular_test/angular_test.dart';
import 'package:angular_tour_of_heroes/app_component.dart';
import 'package:angular_tour_of_heroes/app_component.template.dart' as app_aot;
import 'package:test/test.dart';

import 'app_test.template.dart' as aot;

@GenerateInjector(const [
  const ClassProvider(AppComponent),
])
final InjectorFactory rootInjectorFactory = aot.rootInjectorFactory$Injector;

void main() {
  final testBed = NgTestBed.forComponent<AppComponent>(
    app_aot.AppComponentNgFactory,
    rootInjector: rootInjectorFactory,
  );
  NgTestFixture<AppComponent> fixture;

  setUp(() async { fixture = await testBed.create(); });

  tearDown(disposeAnyRunningTest);

  test('Default greeting', () {
    expect(fixture.text, 'Hello Angular');
  });
  // ...
}
```

Do you see anything obviously wrong?

cc @kwalrath

**Comment by matanlurey** [comment]
This is just a bug. It was fixed in the compiler recently, but we haven't released yet. I'm closing for now, it will be fixed in alpha+7.
