### ISSUE TITLE
Can't use dartdevc with Dart 2 + angular 5.0.0

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/angular#1035]
I would like to use dartdevc with my project, but can't seem to get it working with Dart 2.
Steps to reproduce:

1. create a starter angular project in IntelliJ
2. update dependencies to latest versions:

```
dependencies:
  angular: 5.0.0-alpha+6
  angular_components: 0.9.0-alpha+6
```

3. run `pub serve`
4. observe error:

```
λ pub serve
Loading source assets... 
Loading angular transformers... 
Unable to spawn isolate: The built-in library 'dart:html' is not available on the stand-alone VM.
'package:angular/src/core/application_ref.dart': error: line 2 pos 1: library handler failed
import 'dart:html';
```

*  Dart SDK Version 2.0.0-dev.32.0 
*  AngularDart Version 5.0.0-alpha+6
*  angular_components Version 0.9.0-alpha+6
* MacOSX

**Comment by matanlurey** [comment]
Remove any `transformers: ...` section. That has no effect w/ build_runner.

/cc @jakemac53 @natebosch - should we warn if we see `transformers: ...`?

**Comment by alorenzen** [comment]
Don't use `pub serve`. Use `pub run build_runner serve` instead.

**Comment by natebosch** [comment]
> should we warn if we see transformers: ...?

I'm not quite sure. If someone is transitioning from `pub build` and _not_ using angular, it should be valid to swap between the two options so I don't know  if we want to warn in general with `build_runner`.

Another option to ease the transition for angular specifically is to add back a Transformer which just fails with an error like "You are trying to build angular with `pub`. See docs for running with `build_runner` instead"

**Comment by matanlurey** [comment]
@natebosch I really don't want to add a dependency on barback just to error.

**Comment by johnpryan** [comment]
The error goes away after adding `build_runner` `0.7.13`

Now my app displays "Loading..." but nothing happens

**Comment by jakemac53** [comment]
@johnpryan you probably need a dev dependency on `build_web_compilers`, we should probably make `serve` complain about that if you don't have it.

**Comment by johnpryan** [comment]
Adding `build_web_compilers` changed it from 0 outputs to 3610 outputs. Making progress.

Now I'm seeing an error about the transformers:

```
core.UnsupportedError.new {requireMap: {…}, requireModules: null, requireType: "require", Symbol(UnsupportedError.message): "Using the 'angular' transformer is required.↵↵Plea…r'↵transformer on your application's entry point.", Symbol(_error): Error at Object.dart.throw (http://localhost:8080/packages/$sdk/dev_compiler/amd/dart_sdk.js:490…}
requireMap
:
{prefix: undefined, name: "_@r6", parentMap: undefined, unnormalized: false, url: "/_@r6.js", …}
requireModules
:
null
requireType
:
"require"
Symbol(UnsupportedError.message)
:
"Using the 'angular' transformer is required.↵↵Please see https://webdev.dartlang.org/angular/tutorial for setup instructions,↵and ensure your 'pubspec.yaml' file is configured to invoke the 'angular'↵transformer on your application's entry point."
Symbol(_error)
:
Error at Object.dart.throw (http://localhost:8080/packages/$sdk/dev_compiler/amd/dart_sdk.js:4909:29) at Object.src__platform__bootstrap.bootstrap (http://localhost:8080/packages/angular/src/platform/bootstrap.ddc.js:31:22) at Object.main.main (http://localhost:8080/main.ddc.js:12:30) at http://localhost:8080/main.dart.bootstrap.js:674:12 at Object.execCb (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1696:33) at Module.check (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:878:55) at Module.<anonymous> (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1139:34) at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:134:23 at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1189:21 at each (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:59:31) at Module.emit (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1188:17) at Module.check (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:938:30) at Module.<anonymous> (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1139:34) at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:134:23 at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1189:21 at each (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:59:31) at Module.emit (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1188:17) at Module.check (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:938:30) at Module.<anonymous> (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1139:34) at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:134:23 at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1189:21 at each (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:59:31) at Module.emit (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1188:17) at Module.check (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:938:30) at Module.<anonymous> (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1139:34) at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:134:23 at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1189:21 at each (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:59:31) at Module.emit (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1188:17) at Module.check (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:938:30) at Module.<anonymous> (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1139:34) at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:134:23 at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1189:21 at each (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:59:31) at Module.emit (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1188:17) at Module.check (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:938:30) at Module.<anonymous> (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1139:34) at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:134:23 at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1189:21 at each (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:59:31) at Module.emit (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1188:17) at Module.check (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:938:30) at Module.<anonymous> (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1139:34) at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:134:23 at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1189:21 at each (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:59:31) at Module.emit (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1188:17) at Module.check (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:938:30) at Module.<anonymous> (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1139:34) at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:134:23 at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1189:21 at each (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:59:31) at Module.emit (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1188:17) at Module.check (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:938:30) at Module.<anonymous> (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1139:34) at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:134:23 at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1189:21 at each (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:59:31) at Module.emit (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1188:17) at Module.check (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:938:30) at Module.<anonymous> (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1139:34) at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:134:23 at http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1189:21 at each (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:59:31) at Module.emit (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1188:17) at Module.check (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:938:30) at Module.enable (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1176:22) at Module.init (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:788:26) at callGetModule (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1203:63) at Object.completeLoad (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1590:21) at HTMLScriptElement.onScriptLoad (http://localhost:8080/packages/$sdk/dev_compiler/amd/require.js:1717:29)
hashCode
:
(...)
message
:
(...)
runtimeType
:
(...)
stackTrace
:
(...)
Symbol(dartx.hashCode)
:
(...)
Symbol(dartx.runtimeType)
:
(...)
Symbol(dartx.stackTrace)
:
(...)
__proto__
:
Error
```

**Comment by matanlurey** [comment]
Closer! 

Delete `transformers: ...` entirely. Delete `web: ...` entirely.

Now replace `bootstrap` with `bootstrapStatic`. Here is an example:
https://github.com/dart-lang/angular/blob/master/examples/hello_world/web/main.dart

We'll need to work on a v4->v5 migration guide as part of stabilizing.

**Comment by johnpryan** [comment]
Hmm.. I'm still seeing the `Using the 'angular' transformer is required.↵↵Please see https://webdev.dartlang.org/angular/tutorial for setup instructions,↵and ensure your 'pubspec.yaml' file is configured to invoke the 'angular'↵transformer on your application's entry point.` error with this pubspec:

```yaml
name: openguitar_web
description: A web app that uses AngularDart Components
version: 0.0.1

dependencies:
  angular: 5.0.0-alpha+6
  angular_components: 0.9.0-alpha+6

dev_dependencies:
  build_runner: 0.7.13
  browser: any
  build_web_compilers: any
```

**Comment by johnpryan** [comment]
Got it.

adding `build.debug.yaml` and switching to `bootstrapStatic` fixed it for me.
