### ISSUE TITLE
Following Getting Started: webdev and stagehand appear to be corrupted (Linux)

### ISSUE THREAD

**Issue by jpgilchrist** [dart-lang/angular#1430]
Heads up, I'm not sure if this belongs here or in another repository. Please advise. Thanks in advance.

* [x] Dart SDK Version (`dart --version`)
Dart VM version: 2.0.0-dev.64.1 (Unknown timestamp) on "linux_x64"
* [ ] AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`)
* [x] Whether you are using Windows, macOS, or Linux (if applicable)
Linux
* [ ] Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
* [ ] Any other packages or constraints we should know about

I followed the installation steps here: https://webdev-dartlang-org-dev.firebaseapp.com/guides/get-started

and activated `stagehand` and `webdev`. Afterwards I tried to run `stagehand` to create an app. It failed with the following:

```
$ stagehand
file:///home/jpgilchrist/.pub-cache/global_packages/stagehand/bin/stagehand.dart.snapshot:1:1: Error: Unable to decode bytes as UTF-8.
���ܵl
```

So, I decided to install IntelliJ to create the project. IntelliJ successfully created the project, but then I went to run it with `webdev` and ran into another issue.

```

$ webdev
Crash when formatting: [AsciiControlCharacter] The control character U+001A can only be used in strings and comments.
RangeError (index): Invalid value: Not in range 0..269595, inclusive: 272804
#0      _StringBase.[] (dart:core/runtime/libstring_patch.dart:233:55)
#1      Source.getTextLine (package:kernel/ast.dart:5772:42)
#2      getSourceLine (package:front_end/src/fasta/messages.dart:27:9)
#3      format (package:front_end/src/fasta/command_line_reporting.dart:80:27)
#4      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:206:32)
#5      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:215:22)
#6      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:67:13)
#7      Loader.addMessage (package:front_end/src/fasta/loader.dart:258:20)
#8      Loader.addCompileTimeError (package:front_end/src/fasta/loader.dart:207:5)
#9      LibraryBuilder.addCompileTimeError (package:front_end/src/fasta/builder/library_builder.dart:89:12)
#10     SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:174:17)
<asynchronous suspension>
#11     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:192:26)
<asynchronous suspension>
#12     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:176:13)
<asynchronous suspension>
#13     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:237:20)
<asynchronous suspension>
#14     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:232:24)
<asynchronous suspension>
#15     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:46)
#16     new Future.sync (dart:async/future.dart:222:31)
#17     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:19)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1465:12)
#22     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:117:12)
#23     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:102:20)
<asynchronous suspension>
#24     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:38:44)
<asynchronous suspension>
#25     IncrementalCompilerWrapper.compileInternal (file:///tmp/tmpcU3f4j/dart-2.0.0-dev.64.1/dart/pkg/vm/bin/kernel_service.dart:158:28)
<asynchronous suspension>
#26     Compiler.compile.<anonymous closure> (file:///tmp/tmpcU3f4j/dart-2.0.0-dev.64.1/dart/pkg/vm/bin/kernel_service.dart:132:39)
#27     new Future.<anonymous closure> (dart:async/future.dart:174:37)
#28     _rootRun (dart:async/zone.dart:1122:38)
#29     _CustomZone.run (dart:async/zone.dart:1023:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#35     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#36     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#37     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)

Crash when compiling file:///home/jpgilchrist/.pub-cache/global_packages/webdev/bin/webdev.dart.snapshot,
at character offset 265891:
RangeError (index): Invalid value: Not in range 0..269595, inclusive: 272804
#0      _StringBase.[] (dart:core/runtime/libstring_patch.dart:233:55)
#1      Source.getTextLine (package:kernel/ast.dart:5772:42)
#2      getSourceLine (package:front_end/src/fasta/messages.dart:27:9)
#3      format (package:front_end/src/fasta/command_line_reporting.dart:80:27)
#4      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:206:32)
#5      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:215:22)
#6      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:67:13)
#7      Loader.addMessage (package:front_end/src/fasta/loader.dart:258:20)
#8      Loader.addCompileTimeError (package:front_end/src/fasta/loader.dart:207:5)
#9      LibraryBuilder.addCompileTimeError (package:front_end/src/fasta/builder/library_builder.dart:89:12)
#10     SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:174:17)
<asynchronous suspension>
#11     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:192:26)
<asynchronous suspension>
#12     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:176:13)
<asynchronous suspension>
#13     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:237:20)
<asynchronous suspension>
#14     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:232:24)
<asynchronous suspension>
#15     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:46)
#16     new Future.sync (dart:async/future.dart:222:31)
#17     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:19)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1465:12)
#22     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:117:12)
#23     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:102:20)
<asynchronous suspension>
#24     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:38:44)
<asynchronous suspension>
#25     IncrementalCompilerWrapper.compileInternal (file:///tmp/tmpcU3f4j/dart-2.0.0-dev.64.1/dart/pkg/vm/bin/kernel_service.dart:158:28)
<asynchronous suspension>
#26     Compiler.compile.<anonymous closure> (file:///tmp/tmpcU3f4j/dart-2.0.0-dev.64.1/dart/pkg/vm/bin/kernel_service.dart:132:39)
#27     new Future.<anonymous closure> (dart:async/future.dart:174:37)
#28     _rootRun (dart:async/zone.dart:1122:38)
#29     _CustomZone.run (dart:async/zone.dart:1023:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#35     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#36     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#37     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)


#0      _StringBase.[] (dart:core/runtime/libstring_patch.dart:233:55)
#1      Source.getTextLine (package:kernel/ast.dart:5772:42)
#2      getSourceLine (package:front_end/src/fasta/messages.dart:27:9)
#3      format (package:front_end/src/fasta/command_line_reporting.dart:80:27)
#4      ProcessedOptions.format (package:front_end/src/base/processed_options.dart:206:32)
#5      ProcessedOptions.report (package:front_end/src/base/processed_options.dart:215:22)
#6      CompilerContext.report (package:front_end/src/fasta/compiler_context.dart:67:13)
#7      Loader.addMessage (package:front_end/src/fasta/loader.dart:258:20)
#8      Loader.addCompileTimeError (package:front_end/src/fasta/loader.dart:207:5)
#9      LibraryBuilder.addCompileTimeError (package:front_end/src/fasta/builder/library_builder.dart:89:12)
#10     SourceLoader.tokenize (package:front_end/src/fasta/source/source_loader.dart:174:17)
<asynchronous suspension>
#11     SourceLoader.buildOutline (package:front_end/src/fasta/source/source_loader.dart:192:26)
<asynchronous suspension>
#12     Loader.buildOutlines (package:front_end/src/fasta/loader.dart:176:13)
<asynchronous suspension>
#13     KernelTarget.buildOutlines (package:front_end/src/fasta/kernel/kernel_target.dart:237:20)
<asynchronous suspension>
#14     IncrementalCompiler.computeDelta.<anonymous closure> (package:front_end/src/fasta/incremental_compiler.dart:232:24)
<asynchronous suspension>
#15     CompilerContext.runInContext.<anonymous closure>.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:46)
#16     new Future.sync (dart:async/future.dart:222:31)
#17     CompilerContext.runInContext.<anonymous closure> (package:front_end/src/fasta/compiler_context.dart:118:19)
#18     _rootRun (dart:async/zone.dart:1126:13)
#19     _CustomZone.run (dart:async/zone.dart:1023:19)
#20     _runZoned (dart:async/zone.dart:1518:10)
#21     runZoned (dart:async/zone.dart:1465:12)
#22     CompilerContext.runInContext (package:front_end/src/fasta/compiler_context.dart:117:12)
#23     IncrementalCompiler.computeDelta (package:front_end/src/fasta/incremental_compiler.dart:102:20)
<asynchronous suspension>
#24     IncrementalCompiler.compile (package:vm/incremental_compiler.dart:38:44)
<asynchronous suspension>
#25     IncrementalCompilerWrapper.compileInternal (file:///tmp/tmpcU3f4j/dart-2.0.0-dev.64.1/dart/pkg/vm/bin/kernel_service.dart:158:28)
<asynchronous suspension>
#26     Compiler.compile.<anonymous closure> (file:///tmp/tmpcU3f4j/dart-2.0.0-dev.64.1/dart/pkg/vm/bin/kernel_service.dart:132:39)
#27     new Future.<anonymous closure> (dart:async/future.dart:174:37)
#28     _rootRun (dart:async/zone.dart:1122:38)
#29     _CustomZone.run (dart:async/zone.dart:1023:19)
#30     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#32     _rootRun (dart:async/zone.dart:1126:13)
#33     _CustomZone.run (dart:async/zone.dart:1023:19)
#34     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:949:23)
#35     Timer._createTimer.<anonymous closure> (dart:async/runtime/libtimer_patch.dart:21:15)
#36     _Timer._runTimers (dart:isolate/runtime/libtimer_impl.dart:382:19)
#37     _Timer._handleMessage (dart:isolate/runtime/libtimer_impl.dart:416:5)
#38     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by chalin** [comment]
This is due to a known issue with the 2.0.0-dev.64.1 SDK `pub` command. See https://github.com/dart-lang/stagehand/issues/543#issuecomment-399668142 for workarounds.
