### ISSUE TITLE
The getter 'isBoolNumStringOrNull' was called on null

### ISSUE THREAD

**Issue by lejard-h** [dart-lang/angular#1498]
After upgrading to angular beta from angular alpha and dart-2.0.0-dev68

I have the following error at compile time.

```
NoSuchMethodError: The getter 'isBoolNumStringOrNull' was called on null.
Receiver: null
Tried calling: isBoolNumStringOrNull
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      CodeGenerator._emitSimpleIdentifier (package:dev_compiler/src/analyzer/code_generator.dart:3008:24)
#2      CodeGenerator.visitSimpleIdentifier (package:dev_compiler/src/analyzer/code_generator.dart:2972:20)
#3      CodeGenerator.visitPrefixedIdentifier (package:dev_compiler/src/analyzer/code_generator.dart:5157:14)
#4      PrefixedIdentifierImpl.accept (package:analyzer/src/dart/ast/ast.dart:8952:49)
#5      CodeGenerator._visitExpression (package:dev_compiler/src/analyzer/code_generator.dart:5796:18)
#6      CodeGenerator.visitNamedExpression (package:dev_compiler/src/analyzer/code_generator.dart:4061:46)
#7      CodeGenerator._emitArgumentList (package:dev_compiler/src/analyzer/code_generator.dart:4044:19)
#8      CodeGenerator.visitInstanceCreationExpression.<anonymous closure> (package:dev_compiler/src/analyzer/code_generator.dart:4538:15)
#9      CodeGenerator._emitInstanceCreationExpression.emitNew (package:dev_compiler/src/analyzer/code_generator.dart:4356:31)
#10     CodeGenerator._emitInstanceCreationExpression (package:dev_compiler/src/analyzer/code_generator.dart:4395:51)
#11     CodeGenerator.visitInstanceCreationExpression (package:dev_compiler/src/analyzer/code_generator.dart:4535:12)
#12     InstanceCreationExpressionImpl.accept (package:analyzer/src/dart/ast/ast.dart:6579:15)
#13     CodeGenerator._visitExpression (package:dev_compiler/src/analyzer/code_generator.dart:5796:18)
#14     CodeGenerator._visitInitializer (package:dev_compiler/src/analyzer/code_generator.dart:4283:11)
#15     CodeGenerator._emitLazyFields (package:dev_compiler/src/analyzer/code_generator.dart:4299:19)
#16     CodeGenerator._emitTopLevelFields (package:dev_compiler/src/analyzer/code_generator.dart:4243:21)
#17     CodeGenerator.visitCompilationUnit (package:dev_compiler/src/analyzer/code_generator.dart:638:9)
#18     List.forEach (dart:core/runtime/libarray.dart:79:8)
#19     CodeGenerator._emitModule (package:dev_compiler/src/analyzer/code_generator.dart:384:22)
#20     CodeGenerator.compile (package:dev_compiler/src/analyzer/code_generator.dart:263:18)
#21     ModuleCompiler.compile (package:dev_compiler/src/analyzer/module_compiler.dart:233:28)
#22     _compile (package:dev_compiler/src/analyzer/command.dart:185:25)
#23     compile (package:dev_compiler/src/analyzer/command.dart:57:5)
#24     _CompilerWorker.performRequest (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:43:20)
<asynchronous suspension>
#25     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#26     _rootRun (dart:async/zone.dart:1126:13)
#27     _CustomZone.run (dart:async/zone.dart:1023:19)
#28     _runZoned (dart:async/zone.dart:1518:10)
#29     runZoned (dart:async/zone.dart:1465:12)
#30     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#31     main (file:///b/build/slave/dart-sdk-linux-dev/build/sdk/pkg/dev_compiler/bin/dartdevc.dart:23:64)
<asynchronous suspension>
#32     _startIsolate.<anonymous closure> (dart:isolate/runtime/libisolate_patch.dart:277:32)
#33     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/libisolate_patch.dart:165:12)
```

**Comment by lejard-h** [comment]
I also have warning but don't know if it is linked

```
Selector argument FocusableItem for "@ContentChildren" is a Type, but it is not annotated with @Component or @Directive. During runtime this query will never find any elements. This may become an error in future versions of AngularDart
```

**Comment by matanlurey** [comment]
This issue was moved to dart-lang/sdk#33885
