### ISSUE TITLE
Deferred loading exception when caching via service worker

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/angular#1711]
I'm using a service worker to cache `.js` sources which causes issues with deferred loaded components. I'm getting the exception below. The error goes away if I open developer panel and disable caches.

Is this expected? Is there recommendations on how to integrate service workers in a none-destructive way?

```
core_patch.dart:566 EXCEPTION: DeferredLoadException: 'Loading main.dart.js_2.part.js failed: the code with hash 'HSm/qDEDlQhcchOApeL6rwJl2s4=' was not loaded.
event log:
 - _loadHunk: main.dart.js_15.part.js
 - download: main.dart.js_15.part.js from https://en.projectdomain.app/main.dart.js_15.part.js
 - _loadHunk: main.dart.js_6.part.js
 - download: main.dart.js_6.part.js from https://en.projectdomain.app/main.dart.js_6.part.js
 - download success: main.dart.js_15.part.js
 - initialize: main.dart.js_15.part.js (Jf+ghjCo2KlR7ML9rsOXt9Am8RE=)
 - download success: main.dart.js_6.part.js
 - initialize: main.dart.js_6.part.js (gNKXIF1D2w8g3Kiac0bESHXkWys=)
 - _loadHunk: main.dart.js_2.part.js
 - download: main.dart.js_2.part.js from https://en.projectdomain.app/main.dart.js_2.part.js
 - _loadHunk: main.dart.js_1.part.js
 - download: main.dart.js_1.part.js from https://en.projectdomain.app/main.dart.js_1.part.js
 - download success: main.dart.js_2.part.js
 - missing hunk: main.dart.js_2.part.js (HSm/qDEDlQhcchOApeL6rwJl2s4=)
'
STACKTRACE: 
DeferredLoadException: 'Loading main.dart.js_2.part.js failed: the code with hash 'HSm/qDEDlQhcchOApeL6rwJl2s4=' was not loaded.
event log:
 - _loadHunk: main.dart.js_15.part.js
 - download: main.dart.js_15.part.js from https://en.projectdomain.app/main.dart.js_15.part.js
 - _loadHunk: main.dart.js_6.part.js
 - download: main.dart.js_6.part.js from https://en.projectdomain.app/main.dart.js_6.part.js
 - download success: main.dart.js_15.part.js
 - initialize: main.dart.js_15.part.js (Jf+ghjCo2KlR7ML9rsOXt9Am8RE=)
 - download success: main.dart.js_6.part.js
 - initialize: main.dart.js_6.part.js (gNKXIF1D2w8g3Kiac0bESHXkWys=)
 - _loadHunk: main.dart.js_2.part.js
 - download: main.dart.js_2.part.js from https://en.projectdomain.app/main.dart.js_2.part.js
 - _loadHunk: main.dart.js_1.part.js
 - download: main.dart.js_1.part.js from https://en.projectdomain.app/main.dart.js_1.part.js
 - download success: main.dart.js_2.part.js
 - missing hunk: main.dart.js_2.part.js (HSm/qDEDlQhcchOApeL6rwJl2s4=)
'
    at Object.e (https://en.projectdomain.app/main.dart.js:471:3)
    at U4.$0 (https://en.projectdomain.app/main.dart.js:9786:9)
    at U6.$1 (https://en.projectdomain.app/main.dart.js:9797:8)
    at EO.$1 (https://en.projectdomain.app/main.dart.js:17196:10)
    at In.Ss [as $2$5] (https://en.projectdomain.app/main.dart.js:1888:35)
    at mq.wx (https://en.projectdomain.app/main.dart.js:17148:12)
    at Object.eval (eval at Z5 (https://en.projectdomain.app/main.dart.js:618:15), <anonymous>:3:47)
    at Mz.ho (https://en.projectdomain.app/main.dart.js:11650:12)
    at N_.$0 (https://en.projectdomain.app/main.dart.js:10784:16)
    at Object.kK (https://en.projectdomain.app/main.dart.js:1747:41)

$3 @ core_patch.dart:566
$1 @ application_ref.dart:136
$1 @ ng_zone.dart:143
Ss @ zone.dart:1132
wx @ zone.dart:718
(anonymous) @ VM2670:3
ho @ zone.dart:1029
ix @ zone.dart:931
dV @ stream_impl.dart:336
cp @ stream_impl.dart:263
dV @ broadcast_stream_controller.dart:379
n @ broadcast_stream_controller.dart:254
FU @ ng_zone.dart:187
(anonymous) @ VM2662:3
f7 @ zone.dart:1003
kK @ future_impl.dart:557
cq @ future_impl.dart:494
cq @ future_impl.dart:55
dz @ future_impl.dart:27
(anonymous) @ VM2759:3
$2 @ ng_zone.dart:155
Sr @ zone.dart:1144
GS @ zone.dart:725
(anonymous) @ VM2668:3
t8 @ zone.dart:1037
Ke @ future_impl.dart:143
$0 @ future_impl.dart:654
kK @ future_impl.dart:675
cq @ future_impl.dart:494
cq @ future_impl.dart:55
dz @ future_impl.dart:27
dz @ async_patch.dart:213
I @ async_patch.dart:295
(anonymous) @ router_impl.dart:157
(anonymous) @ async_patch.dart:333
$2 @ async_patch.dart:357
$2 @ async_patch.dart:313
$2 @ ng_zone.dart:155
Sr @ zone.dart:1144
GS @ zone.dart:725
(anonymous) @ VM2668:3
t8 @ zone.dart:1037
Ke @ future_impl.dart:143
$0 @ future_impl.dart:654
kK @ future_impl.dart:675
cq @ future_impl.dart:494
cq @ future_impl.dart:55
dz @ future_impl.dart:27
dz @ async_patch.dart:213
I @ async_patch.dart:295
(anonymous) @ router_impl.dart:257
(anonymous) @ async_patch.dart:333
$2 @ async_patch.dart:357
$2 @ async_patch.dart:313
$2 @ ng_zone.dart:155
Sr @ zone.dart:1144
GS @ zone.dart:725
(anonymous) @ VM2668:3
t8 @ zone.dart:1037
Ke @ future_impl.dart:143
$0 @ future_impl.dart:654
kK @ future_impl.dart:675
cq @ future_impl.dart:494
cq @ future_impl.dart:55
dz @ future_impl.dart:27
dz @ async_patch.dart:213
I @ async_patch.dart:295
(anonymous) @ root_component.dart:51
(anonymous) @ async_patch.dart:333
$2 @ async_patch.dart:357
$2 @ async_patch.dart:313
$2 @ ng_zone.dart:155
Sr @ zone.dart:1144
GS @ zone.dart:725
(anonymous) @ VM2668:3
t8 @ zone.dart:1037
Ke @ future_impl.dart:143
$0 @ future_impl.dart:654
kK @ future_impl.dart:675
cq @ future_impl.dart:494
$2 @ future.dart:385
$2 @ ng_zone.dart:155
Sr @ zone.dart:1144
GS @ zone.dart:725
(anonymous) @ VM2668:3
t8 @ zone.dart:1037
Ke @ future_impl.dart:143
$0 @ future_impl.dart:654
kK @ future_impl.dart:675
oS @ future_impl.dart:486
$0 @ future_impl.dart:516
$0 @ ng_zone.dart:116
$0 @ ng_zone.dart:131
Sq @ zone.dart:1124
wu @ zone.dart:711
(anonymous) @ VM2666:3
c3 @ zone.dart:1021
hn @ zone.dart:923
$0 @ zone.dart:963
a9S @ schedule_microtask.dart:41
aa4 @ schedule_microtask.dart:50
$1 @ async_patch.dart:49
adl @ js_helper.dart:2272
(anonymous) @ js_helper.dart:2306
childList (async)
$1 @ async_patch.dart:63
a1W @ async_patch.dart:27
St @ zone.dart:1185
FO @ zone.dart:763
(anonymous) @ VM2672:3
fu @ zone.dart:1080
bt @ future_impl.dart:515
bi @ future_impl.dart:40
$0 @ js_helper.dart:3987
adl @ js_helper.dart:2270
(anonymous) @ js_helper.dart:2306
load (async)
a9L @ js_helper.dart:4052
$1 @ js_helper.dart:3883
p2 @ list.dart:162
eo @ js_helper.dart:3889
(anonymous) @ root_component.dart:53
(anonymous) @ async_patch.dart:333
$2 @ async_patch.dart:357
K @ async_patch.dart:249
U2 @ root_component.dart:51
ph @ router_impl.dart:339
(anonymous) @ router_impl.dart:268
(anonymous) @ async_patch.dart:333
$2 @ async_patch.dart:357
K @ async_patch.dart:249
GK @ router_impl.dart:257
iJ @ router_impl.dart:257
GJ @ router_impl.dart:240
(anonymous) @ router_impl.dart:184
(anonymous) @ async_patch.dart:333
$2 @ async_patch.dart:357
$1 @ async_patch.dart:308
$1 @ ng_zone.dart:143
Ss @ zone.dart:1132
wx @ zone.dart:718
(anonymous) @ VM2670:3
ho @ zone.dart:1029
$0 @ future_impl.dart:129
kK @ future_impl.dart:671
$0 @ future_impl.dart:351
$0 @ ng_zone.dart:116
$0 @ ng_zone.dart:131
Sq @ zone.dart:1124
wu @ zone.dart:711
(anonymous) @ VM2666:3
c3 @ zone.dart:1021
hn @ zone.dart:923
$0 @ zone.dart:963
a9S @ schedule_microtask.dart:41
aa4 @ schedule_microtask.dart:50
$1 @ async_patch.dart:49
adl @ js_helper.dart:2272
(anonymous) @ js_helper.dart:2306
childList (async)
$1 @ async_patch.dart:63
a1W @ async_patch.dart:27
St @ zone.dart:1185
FO @ zone.dart:763
(anonymous) @ VM2672:3
fu @ zone.dart:1080
mb @ future_impl.dart:350
qi @ future_impl.dart:259
fk @ future_impl.dart:252
az @ future_impl.dart:241
p6 @ router_impl.dart:141
LU @ router_impl.dart:109
br @ router_impl.dart:104
NC @ root_component.dart:306
pv @ root_component.template.dart:1601
(anonymous) @ VM2824:3
$0 @ app_view.dart:608
$0 @ ng_zone.dart:131
Sq @ zone.dart:1120
wu @ zone.dart:711
(anonymous) @ VM2666:3
c3 @ zone.dart:1021
hn @ zone.dart:923
$1 @ ng_zone.dart:299
$1 @ ng_zone.dart:143
Ss @ zone.dart:1132
wx @ zone.dart:718
(anonymous) @ VM2670:3
ho @ zone.dart:1029
ix @ zone.dart:931
dV @ stream_impl.dart:336
cp @ stream_impl.dart:263
dV @ broadcast_stream_controller.dart:379
n @ broadcast_stream_controller.dart:254
j3 @ button_decorator.dart:86
(anonymous) @ VM2691:3
$0 @ app_view.dart:608
$0 @ ng_zone.dart:131
Sq @ zone.dart:1124
wu @ zone.dart:711
(anonymous) @ VM2666:3
c3 @ zone.dart:1021
hn @ zone.dart:923
$1 @ ng_zone.dart:299
adl @ js_helper.dart:2272
(anonymous) @ js_helper.dart:2306
```

**Comment by matanlurey** [comment]
I am closing due to lack of response.
