### ISSUE TITLE
angular_analyzer_plugin doesn't working correctly - NoSuchMethodError: The method 'send' was called on null.

### ISSUE THREAD

**Issue by supermuka** [dart-lang/angular#1882]
* Dart SDK Version (`dart --version`)
`2.7.0`
* AngularDart Version (i.e. `4.0.0`, `5.0.0-alpha+5`, `MASTER`)
`angular: ^6.0.0-alpha+1`
* Whether you are using Windows, macOS, or Linux (if applicable)
`Windows 10`
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
`Chrome`
* Any other packages or constraints we should know about
`Intellij IDEA 2019.3.3`

`angular_analyzer_plugin` doesn't working correctly. 

According to [Troubleshooting](https://github.com/dart-lang/angular/tree/master/angular_analyzer_plugin#troubleshooting), I did the following test: 

> If you run bin/plugin.dart from .plugin_manager/HASH/analyzer_plugin, do you get any import errors? (Note: this is expected to crash when launched in this way, but without import-related errors)

And it shown this error:

> C:\Users\samue\AppData\Local\.dartServer\.plugin_manager\7b2b624ba25bf337c9e3e051bc8ef6c2\analyzer_plugin\bin>dart plugin.dart
> Unhandled exception:
> NoSuchMethodError: The method 'send' was called on null.
> Receiver: null
> Tried calling: send(SendPort)
> #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:53:5)
> #1      new PluginIsolateChannel (package:analyzer_plugin/src/channel/isolate_channel.dart:109:15)
> #2      Driver.start (package:analyzer_plugin/src/driver.dart:30:40)
> #3      start (package:angular_analyzer_plugin/starter.dart:9:8)
> #4      main (file:///C:/Users/samue/AppData/Local/.dartServer/.plugin_manager/7b2b624ba25bf337c9e3e051bc8ef6c2/analyzer_plugin/bin/plugin.dart:7:3)
> #5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
> #6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

**Comment by supermuka** [comment]
The angular_analyzer is working again after last updates in Dart plugin/IntelliJ and packages.
