### ISSUE TITLE
Generate helpful message if child query annotation is missing a selector

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/angular#519]
We should log a severe level message informing the user they need a selector if a child query is missing one, rather than letting the following exception occur.

```dart
@Component(
)
class AppCompoennt {
  @ViewChild() // <-- missing selector causes the following exception.
  ChildComponent child;
}
```

```
[BuilderTransformer: GeneratorBuilder:[TemplateGenerator] on playground|lib/app_component.dart]:
Error running TemplateGenerator for .
Error: NoSuchMethodError: The method 'toTypeValue' was called on null.
Receiver: null
Tried calling: toTypeValue()
Stack Trace:
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      ComponentVisitor._getSelectors (package:angular/src/source_gen/template_compiler/find_components.dart:291)
#3      ComponentVisitor._getQuery (package:angular/src/source_gen/template_compiler/find_components.dart:314)
#4      ComponentVisitor._visitClassMember (package:angular/src/source_gen/template_compiler/find_components.dart:268)

```

**Comment by matanlurey** [comment]
Closed in https://github.com/dart-lang/angular/pull/1079.
