### ISSUE TITLE
Async routing is not working

### ISSUE THREAD

**Issue by alexd1971** [dart-lang/angular#623]
There is a [sample application](https://github.com/kulshekhar/angular-dart-routing-lazy-loading) how to create asyncronous routing with angular2. It works fine. Trying to adopt it to angular v4.0.0 fails with following error in the browser console:
```
html_dart2js.dart:3558 EXCEPTION: No precompiled component C2Component found
STACKTRACE: 
No precompiled component C2Component found
    at Object.wrapException (http://localhost:8080/main.dart.js:2928:17)
    at ReflectorComponentResolver.resolveComponentSync$1 (http://localhost:8080/main.dart.js:15466:19)
    at Object.getComponentAnnotations (http://localhost:8080/main.dart.js:20330:30)
    at RouteRegistry.configFromComponent$1 (http://localhost:8080/main.dart.js:18487:25)
    at http://localhost:8080/main.dart.js:18395:38
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:8080/main.dart.js:5489:15)
    at _wrapJsFunctionForAsync_closure.dart._wrapJsFunctionForAsync_closure.call$2 (http://localhost:8080/main.dart.js:5919:14)
    at _awaitOnObject_closure.dart._awaitOnObject_closure.call$1 (http://localhost:8080/main.dart.js:5907:34)
    at StaticClosure.dart._rootRunUnary.func (http://localhost:8080/main.dart.js:5763:18)
    at _ZoneDelegate.runUnary$3 (http://localhost:8080/main.dart.js:7689:41)
ORIGINAL EXCEPTION: No precompiled component C2Component found
```

**Comment by eredo** [comment]
You'll need to use the generated `.template.dart` file within your deferred loading factory.
See #606 

As an example:

```dart
import 'package:angular_router/angular_router.dart';
import 'dart:async';

// ignore: uri_has_not_been_generated
import 'my_view.template.dart' deferred as my_view;

Future<dynamic> myViewLoader() async {
  await my_view.loadLibrary();
  my_view.initReflector();
  return my_view.MyComponent;
}

const AsyncRoute userViewRoute = const AsyncRoute(
  name: 'View',
  path: 'view/...',
  loader: myViewLoader,
);
```

**Comment by matanlurey** [comment]
Thanks @eredo - yes @alexd1971 Eric is correct.

There is another related example here (not router-specific):
https://github.com/dart-lang/angular/blob/master/doc/component_loading.md#deferred-loading
