### ISSUE TITLE
angular_router 2: JsObject has no instance getter 'queryParameters' under Dartium

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#635]
I'm [upgrading](https://github.com/dart-lang/site-webdev/issues/1058) toh-5, [the Angular tutorial example that introduced the router](https://webdev.dartlang.org/angular/tutorial/toh-pt5), to use the angular_router 2.0.

The upgraded app **runs fine under Chrome**, but under **Dartium** the following **exception** is thrown:
```nocode
VM44:1 EXCEPTION: Unhandled exception:
NoSuchMethodError: Class 'JsObject' has no instance getter 'queryParameters'.
Receiver: Instance of 'JsObject'
Tried calling: queryParameters
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      new _RouterJs.<anonymous closure> (package:angular_router/src/router/router_coordinator.dart:86:57)
#3      JsObject._callMethodLegacy (dart:js:1282)
#4      JsObject.callMethod (dart:js:1271)
#5      _RouterJs.navigate (package:angular_router/src/router/router_coordinator.dart:102:15)
#6      RouterCoordinator.navigate (package:angular_router/src/router/router_coordinator.dart:50:14)
<asynchronous suspension>
#7      RouterImpl.navigate (package:angular_router/src/router/router_impl.dart:102:39)
#8      RouterLink.onClick (package:angular_router/src/directives/router_link_directive.dart:56:15)
#9      AppView.eventHandler1.<anonymous closure>.<anonymous closure> (package:angular/src/core/linker/app_view.dart:594:38)
#10     _rootRun (dart:async/zone.dart:1120)
#11     _ZoneDelegate.run (dart:async/zone.dart:675)
#12     NgZone._run (package:angular/src/core/zone/ng_zone.dart:175:21)
#13     _CustomZone.run (dart:async/zone.dart:1001)
#14     _CustomZone.runGuarded (dart:async/zone.dart:901)
#15     NgZone.runGuarded (package:angular/src/core/zone/ng_zone.dart:310:23)
#16     AppView.eventHandler1.<anonymous closure> (package:angular/src/core/linker/app_view.dart:594:14)
#17     DebugAppView.eventHandler1.<anonymous closure> (package:angular/src/debug/debug_app_view.dart:164:44)
```

I don't have the updated code out in a PR yet, but I will shortly (as soon as I'm done upgrading the component tests).

cc @kwalrath @matanlurey

**Comment by leonsenft** [comment]
Closed by https://github.com/dart-lang/angular/commit/b124d8b4810e3cb09506a1710ffb5dbb09880750
