### ISSUE TITLE
angular_router 2: JsObject has no instance getter 'queryParameters' when testing

### ISSUE THREAD

**Issue by chalin** [dart-lang/angular#654]
I'm getting the same exception as reported in #635, but this time under **Chrome** when running tests using angular_router 2.0.0-alpha (Dart 1.24.2, Angular 4.0.0). I'll post a link to the tests soon.

Here is the exception:
```nocode
00:01 +0 -11: test/all_test.dart: app: Deep linking: navigate to heroes [E]
Unhandled exception:
NoSuchMethodError: Class 'JsObject' has no instance getter 'queryParameters'.
Receiver: Instance of 'JsObject'
Tried calling: queryParameters
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:43)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      new _RouterJs.<anonymous closure> (package:angular_router/src/router/router_coordinator.dart:86:57)
#3      JsObject._callMethodLegacy (dart:js:1282)
#4      JsObject.callMethod (dart:js:1271)
#5      _RouterJs.navigate (package:angular_router/src/router/router_coordinator.dart:102:15)
#6      RouterCoordinator.navigate (package:angular_router/src/router/router_coordinator.dart:50:14)
<asynchronous suspension>
#7      RouterImpl.navigate (package:angular_router/src/router/router_impl.dart:106:39)
#8      RouterImpl.navigateRouter (package:angular_router/src/router/router_impl.dart:151:14)
<asynchronous suspension>
#9      RouterImpl.registerRootOutlet (package:angular_router/src/router/router_impl.dart:81:7)
#10     RouterOutlet.ngOnInit (package:angular_router/src/directives/router_outlet_directive.dart:93:31)
#11     ViewAppComponent0.detectChangesInternal (package:angular_tour_of_heroes/app_component.template.dart:180:26)
...
```

cc @kwalrath @alorenzen

**Comment by chalin** [comment]
The component tests that are failing are from this commit: https://github.com/dart-lang/site-webdev/pull/1076/commits/55c1a05c5629920858b0cf443908b81d0e1f00db. Specifically all the tests from `examples/ng/doc/toh-5/test/app.dart` (which is run via `all_test.dart`).

**Comment by chalin** [comment]
@matanlurey @alorenzen: I'm still seeing this same error under **Dart 2-dev and Angular 5-alpha**.

**Comment by jimmyff** [comment]
I also get this issue when running my application, router version: 2.0.0-alpha

Error and code:
https://gist.github.com/jimmyff/7494711c0f6fbc103aa7bbe4a1ef8992
