### ISSUE TITLE
Expression parser crashes on _checkNoInterpolation

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/angular#847]
Stack trace from @jimmyff: https://pastebin.com/WaMZUrNg

**Comment by jimmyff** [comment]
I'm trying to migrate from angular 4 + router 1 to angular 5 + router 2. I'm getting this error when running `pub run build_runner serve`.

Component source files: (github wouldn't allow me to upload the .dart file directly)
[upgrade-dialog_component.zip](https://github.com/dart-lang/angular/files/1703840/upgrade-dialog_component.zip)

Error stacktrace:
```
[SEVERE] Instance of 'LibraryBuilder' on datingnode_app_angular|lib/src/components/upgrade_dialog/upgrade_dialog_component.dart: Error running TemplateGenerator for datingnode_app_angular|lib/src/components/upgrade_dialog/upgrade_dialog_component.dart.
Invalid argument(s)
#0      _RegExp.allMatches (dart:core-patch/dart:core/regexp_patch.dart:148)
#1      jsSplit (package:angular/src/facade/lang.dart:7:28)
#2      Parser._checkNoInterpolation (package:angular/src/compiler/expression_parser/parser.dart:182:17)
#3      Parser.parseAction (package:angular/src/compiler/expression_parser/parser.dart:77:10)
#4      _BindDirectivesVisitor.visitEvent (package:angular/src/compiler/ast_template_parser.dart:382:50)
#5      SyntheticTemplateAst&EventAst.accept (package:angular_ast/src/ast/event.dart:59:20)
#6      _BindDirectivesVisitor._visitAll (package:angular/src/compiler/ast_template_parser.dart:495:27)
#7      _BindDirectivesVisitor.visitElement (package:angular/src/compiler/ast_template_parser.dart:262:9)
#8      SyntheticTemplateAst&ElementAst.accept (package:angular_ast/src/ast/element.dart:100:20)
#9      _BindDirectivesVisitor._visitAll (package:angular/src/compiler/ast_template_parser.dart:495:27)
#10     _BindDirectivesVisitor.visitElement (package:angular/src/compiler/ast_template_parser.dart:267:9)
#11     SyntheticTemplateAst&ElementAst.accept (package:angular_ast/src/ast/element.dart:100:20)
#12     _BindDirectivesVisitor._visitAll (package:angular/src/compiler/ast_template_parser.dart:495:27)
#13     _BindDirectivesVisitor.visitElement (package:angular/src/compiler/ast_template_parser.dart:267:9)
#14     SyntheticTemplateAst&ElementAst.accept (package:angular_ast/src/ast/element.dart:100:20)
#15     _BindDirectivesVisitor._visitAll (package:angular/src/compiler/ast_template_parser.dart:495:27)
#16     _BindDirectivesVisitor.visitElement (package:angular/src/compiler/ast_template_parser.dart:267:9)
#17     SyntheticTemplateAst&ElementAst.accept (package:angular_ast/src/ast/element.dart:100:20)
#18     _BindDirectivesVisitor._visitAll (package:angular/src/compiler/ast_template_parser.dart:495:27)
#19     _BindDirectivesVisitor.visitElement (package:angular/src/compiler/ast_template_parser.dart:267:9)
#20     SyntheticTemplateAst&ElementAst.accept (package:angular_ast/src/ast/element.dart:100:20)
#21     _BindDirectivesVisitor._visitAll (package:angular/src/compiler/ast_template_parser.dart:495:27)
#22     AstTemplateParser._bindDirectives (package:angular/src/compiler/ast_template_parser.dart:147:20)
#23     AstTemplateParser._bindDirectivesAndProviders (package:angular/src/compiler/ast_template_parser.dart:106:9)
#24     AstTemplateParser.parse (package:angular/src/compiler/ast_template_parser.dart:66:26)
#25     OfflineCompiler._compileComponent (package:angular/src/compiler/offline_compiler.dart:181:56)
#26     OfflineCompiler.compile (package:angular/src/compiler/offline_compiler.dart:100:32)
#27     processTemplates.<anonymous closure> (package:angular/src/source_gen/template_compiler/template_processor.dart:74:29)
#28     logElapsedSync (package:angular/src/source_gen/common/logging.dart:26:27)
#29     processTemplates (package:angular/src/source_gen/template_compiler/template_processor.dart:73:29)
<asynchronous suspension>
#30     TemplateGenerator.generate.<anonymous closure> (package:angular/src/source_gen/template_compiler/generator.dart:28:27)
<asynchronous suspension>
#31     _rootRun (dart:async/zone.dart:1126)
#32     _CustomZone.run (dart:async/zone.dart:1023)
#33     runZoned (dart:async/zone.dart:1501)
#34     TemplateGenerator.generate (package:angular/src/source_gen/template_compiler/generator.dart:27:12)
<asynchronous suspension>
#35     _generate (package:source_gen/src/builder.dart:224:35)
<asynchronous suspension>
#36     _Builder._generateForLibrary (package:source_gen/src/builder.dart:83:15)
<asynchronous suspension>
#37     _Builder.build (package:source_gen/src/builder.dart:73:11)
<asynchronous suspension>
#38     runBuilder.buildForInput (package:build/src/generate/run_builder.dart:43:21)
<asynchronous suspension>
#39     MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#40     ListIterator.moveNext (dart:_internal/iterable.dart:342)
#41     Future.wait (dart:async/future.dart:385)
#42     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:49:36)
#43     _rootRun (dart:async/zone.dart:1126)
#44     _CustomZone.run (dart:async/zone.dart:1023)
#45     runZoned (dart:async/zone.dart:1490)
#46     scopeLogAsync (package:build/src/builder/logging.dart:20:3)
#47     runBuilder (package:build/src/generate/run_builder.dart:49:9)
<asynchronous suspension>
#48     BuildImpl._runForInput (package:build_runner/src/generate/build_impl.dart:362:11)
<asynchronous suspension>
#49     BuildImpl._runBuilder.<anonymous closure> (package:build_runner/src/generate/build_impl.dart:294:9)
#50     MappedIterator.moveNext (dart:_internal/iterable.dart:391)
#51     Future.wait (dart:async/future.dart:385)
#52     BuildImpl._runBuilder (package:build_runner/src/generate/build_impl.dart:293:36)
<asynchronous suspension>
#53     BuildImpl._runPhases.<anonymous closure> (package:build_runner/src/generate/build_impl.dart:239:30)
<asynchronous suspension>
#54     BuildActionTracker.track (package:build_runner/src/generate/performance_tracker.dart:68:21)
#55     BuildPerformanceTracker.trackAction (package:build_runner/src/generate/performance_tracker.dart:46:20)
#56     BuildImpl._runPhases (package:build_runner/src/generate/build_impl.dart:236:32)
<asynchronous suspension>
#57     BuildImpl._safeBuild.<anonymous closure>.<anonymous closure> (package:build_runner/src/generate/build_impl.dart:207:43)
#58     logTimedAsync (package:build_runner/src/logging/logging.dart:26:30)
<asynchronous suspension>
#59     BuildImpl._safeBuild.<anonymous closure> (package:build_runner/src/generate/build_impl.dart:206:26)
<asynchronous suspension>
#60     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:101:24)
#61     _rootRun (dart:async/zone.dart:1126)
#62     _CustomZone.run (dart:async/zone.dart:1023)
#63     runZoned (dart:async/zone.dart:1501)
#64     Chain.capture (package:stack_trace/src/chain.dart:99:12)
#65     BuildImpl._safeBuild (package:build_runner/src/generate/build_impl.dart:204:11)
#66     BuildImpl.run (package:build_runner/src/generate/build_impl.dart:153:24)
<asynchronous suspension>
#67     WatchImpl._run.doBuild (package:build_runner/src/generate/watch_impl.dart:189:20)
<asynchronous suspension>
#68     WatchImpl._recordCurrentBuild.<anonymous closure> (package:build_runner/src/generate/watch_impl.dart:271:27)
#69     _asyncMapThen.<anonymous closure> (package:stream_transform/src/async_map_buffer.dart:47:16)
#70     _StreamTransformer.bind.<anonymous closure>.<anonymous closure> (package:stream_transform/src/from_handlers.dart:59:58)
#71     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
#72     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#73     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#74     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#75     _StreamController._add (dart:async/stream_controller.dart:639)
#76     _StreamController.add (dart:async/stream_controller.dart:585)
#77     _Buffer.bind.emit (package:stream_transform/src/buffer.dart:46:18)
#78     _Buffer.bind.onTrigger (package:stream_transform/src/buffer.dart:73:39)
#79     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
#80     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#81     _DelayedData.perform (dart:async/stream_impl.dart:578)
#82     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:694)
#83     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654)
#84     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#85     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#86     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:112)
#87     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by matanlurey** [comment]
I'll take a look, thanks!

**Comment by matanlurey** [comment]
Off-hand @jimmyff it looks like this:

><material-button (raised) (trigger)="dismissAction()" autoFocus class="primary">Continue <glyph icon="chevron_right"  size="small"></glyph></material-button>

I think you meant `[raised]` or `raised` not `(raised)`. We shouldn't crash, though.

**Comment by matanlurey** [comment]
I ... think `(raised)` should never be legal, and probably the AST parser should reject it.

/cc @alorenzen @leonsenft @chalin WDUT?

**Comment by matanlurey** [comment]
I have a fix, I believe, rather it will tell you what the error is instead of crashing.

**Comment by chalin** [comment]
> I think you meant [raised] or raised

Right, it should be just `raised`.

> I ... think (raised) should never be legal

You mean `(foo)` w/o an assigned (non-empty) expression? That seems reasonable.

**Comment by jimmyff** [comment]
yep, my bad! Thanks for tracking down my mistake @matanlurey !

**Comment by matanlurey** [comment]
Fixed by https://github.com/dart-lang/angular/commit/51a33791b8a36c6a2f9f54c70681b91b7290e292.
