### ISSUE TITLE
ParseErrorLevel.FATAL: No provider for NgControl

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/angular#856]
I'm migrating from pub, angular4 & router1 to ddc+build_runner, angular5 and router2. I'm getting this issue with one of my components:

Error: `ParseErrorLevel.FATAL: No provider for NgControl`

### Component + directives: 
```
@Component(
  selector: 'settings',
  templateUrl: 'settings_component.html',
  pipes: const [COMMON_PIPES],
  directives: const <dynamic>[
    formDirectives,
    CORE_DIRECTIVES,
    routerDirectives,
    materialDirectives,
    MaterialExpansionPanel,
    MaterialExpansionPanelSet,
    ToolbarComponent
  ],
  changeDetection: ChangeDetectionStrategy.OnPush,
)
```

### Component source files:
[settings-component.zip](https://github.com/dart-lang/angular/files/1706596/settings-component.zip)

### Stack trace:
```
[SEVERE] Instance of 'LibraryBuilder' on datingnode_app_angular|lib/src/components/screens/settings/settings_component.dart: Error running TemplateGenerator for datingnode_app_angular|lib/src/components/screens/settings/settings_component.dart.
Template parse errors:
line 119, column 13 of SettingsComponent: ParseErrorLevel.FATAL: No provider for NgControl
            <material-input
            ^^^^^^^^^^^^^^^^
#0      handleParseErrors (package:angular/src/compiler/template_parser.dart:188:5)
#1      _AstExceptionHandler.maybeReportExceptions (package:angular/src/compiler/ast_template_parser.dart:218:7)
#2      AstTemplateParser.parse (package:angular/src/compiler/ast_template_parser.dart:68:22)
#3      OfflineCompiler._compileComponent (package:angular/src/compiler/offline_compiler.dart:181:56)
#4      OfflineCompiler.compile (package:angular/src/compiler/offline_compiler.dart:100:32)
#5      processTemplates.<anonymous closure> (package:angular/src/source_gen/template_compiler/template_processor.dart:74:29)
#6      logElapsedSync (package:angular/src/source_gen/common/logging.dart:26:27)
#7      processTemplates (package:angular/src/source_gen/template_compiler/template_processor.dart:73:29)
<asynchronous suspension>
#8      TemplateGenerator.generate.<anonymous closure> (package:angular/src/source_gen/template_compiler/generator.dart:28:27)
<asynchronous suspension>
#9      _rootRun (dart:async/zone.dart:1126)
#10     _CustomZone.run (dart:async/zone.dart:1023)
#11     runZoned (dart:async/zone.dart:1501)
#12     TemplateGenerator.generate (package:angular/src/source_gen/template_compiler/generator.dart:27:12)
<asynchronous suspension>
#13     _generate (package:source_gen/src/builder.dart:224:35)
<asynchronous suspension>
#14     _Builder._generateForLibrary (package:source_gen/src/builder.dart:83:15)
<asynchronous suspension>
#15     _Builder.build (package:source_gen/src/builder.dart:73:11)
<asynchronous suspension>
#16     runBuilder.buildForInput (package:build/src/generate/run_builder.dart:43:21)
<asynchronous suspension>
#17     MappedListIterable.elementAt (dart:_internal/iterable.dart:413)
#18     ListIterator.moveNext (dart:_internal/iterable.dart:342)
#19     Future.wait (dart:async/future.dart:385)
#20     runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:49:36)
#21     _rootRun (dart:async/zone.dart:1126)
#22     _CustomZone.run (dart:async/zone.dart:1023)
#23     runZoned (dart:async/zone.dart:1490)
#24     scopeLogAsync (package:build/src/builder/logging.dart:20:3)
#25     runBuilder (package:build/src/generate/run_builder.dart:49:9)
<asynchronous suspension>
#26     BuildImpl._runForInput (package:build_runner/src/generate/build_impl.dart:362:11)
<asynchronous suspension>
#27     BuildImpl._runBuilder.<anonymous closure> (package:build_runner/src/generate/build_impl.dart:294:9)
#28     MappedIterator.moveNext (dart:_internal/iterable.dart:391)
#29     Future.wait (dart:async/future.dart:385)
#30     BuildImpl._runBuilder (package:build_runner/src/generate/build_impl.dart:293:36)
<asynchronous suspension>
#31     BuildImpl._runPhases.<anonymous closure> (package:build_runner/src/generate/build_impl.dart:239:30)
<asynchronous suspension>
#32     BuildActionTracker.track (package:build_runner/src/generate/performance_tracker.dart:68:21)
#33     BuildPerformanceTracker.trackAction (package:build_runner/src/generate/performance_tracker.dart:46:20)
#34     BuildImpl._runPhases (package:build_runner/src/generate/build_impl.dart:236:32)
<asynchronous suspension>
#35     BuildImpl._safeBuild.<anonymous closure>.<anonymous closure> (package:build_runner/src/generate/build_impl.dart:207:43)
#36     logTimedAsync (package:build_runner/src/logging/logging.dart:26:30)
<asynchronous suspension>
#37     BuildImpl._safeBuild.<anonymous closure> (package:build_runner/src/generate/build_impl.dart:206:26)
<asynchronous suspension>
#38     Chain.capture.<anonymous closure> (package:stack_trace/src/chain.dart:101:24)
#39     _rootRun (dart:async/zone.dart:1126)
#40     _CustomZone.run (dart:async/zone.dart:1023)
#41     runZoned (dart:async/zone.dart:1501)
#42     Chain.capture (package:stack_trace/src/chain.dart:99:12)
#43     BuildImpl._safeBuild (package:build_runner/src/generate/build_impl.dart:204:11)
#44     BuildImpl.run (package:build_runner/src/generate/build_impl.dart:153:24)
<asynchronous suspension>
#45     WatchImpl._run.doBuild (package:build_runner/src/generate/watch_impl.dart:189:20)
<asynchronous suspension>
#46     WatchImpl._recordCurrentBuild.<anonymous closure> (package:build_runner/src/generate/watch_impl.dart:271:27)
#47     _asyncMapThen.<anonymous closure> (package:stream_transform/src/async_map_buffer.dart:47:16)
#48     _StreamTransformer.bind.<anonymous closure>.<anonymous closure> (package:stream_transform/src/from_handlers.dart:59:58)
#49     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
#50     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#51     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:257)
#52     _StreamController&&_SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:763)
#53     _StreamController._add (dart:async/stream_controller.dart:639)
#54     _StreamController.add (dart:async/stream_controller.dart:585)
#55     _Buffer.bind.emit (package:stream_transform/src/buffer.dart:46:18)
#56     _Buffer.bind.onTrigger (package:stream_transform/src/buffer.dart:73:39)
#57     _RootZone.runUnaryGuarded (dart:async/zone.dart:1316)
#58     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:330)
#59     _DelayedData.perform (dart:async/stream_impl.dart:578)
#60     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:694)
#61     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:654)
#62     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#63     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#64     _runPendingImmediateCallback (dart:isolate-patch/dart:isolate/isolate_patch.dart:112)
#65     _RawReceivePortImpl._handleMessage (dart:isolate-patch/dart:isolate/isolate_patch.dart:165)
```

**Comment by matanlurey** [comment]
Sorry for the delay. Please let us know if this issue is still present.
