### ISSUE TITLE
Deferred loading not yet supported in build_runner

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/angular#954]
I see this exception from the devtools console when clicking on the 'comments' link for an item on the front page:

```
DeferredLoadException: 'Loading main.dart.js_1.part.js failed: the code with hash 'RFPdwhA3LPHF0px4JXTX46Eyedw=' was not loaded.
event log:
 - _loadHunk: main.dart.js_1.part.js
 - download: main.dart.js_1.part.js from https://dart-hn.firebaseapp.com/main.dart.js_1.part.js
 - download success: main.dart.js_1.part.js
 - missing hunk: main.dart.js_1.part.js (RFPdwhA3LPHF0px4JXTX46Eyedw=)
'
STACKTRACE: 
DeferredLoadException: 'Loading main.dart.js_1.part.js failed: the code with hash 'RFPdwhA3LPHF0px4JXTX46Eyedw=' was not loaded.
event log:
 - _loadHunk: main.dart.js_1.part.js
 - download: main.dart.js_1.part.js from https://dart-hn.firebaseapp.com/main.dart.js_1.part.js
 - download success: main.dart.js_1.part.js
 - missing hunk: main.dart.js_1.part.js (RFPdwhA3LPHF0px4JXTX46Eyedw=)
'
    at Object.a (https://dart-hn.firebaseapp.com/main.dart.js:508:3)
    at oI.$0 (https://dart-hn.firebaseapp.com/main.dart.js:5410:9)
    at oK.$1 (https://dart-hn.firebaseapp.com/main.dart.js:5421:8)
    at kU.qh (https://dart-hn.firebaseapp.com/main.dart.js:1660:35)
    at dp.ir (https://dart-hn.firebaseapp.com/main.dart.js:10278:7)
    at Object.eval (eval at qX (https://dart-hn.firebaseapp.com/main.dart.js:656:15), <anonymous>:2:43)
    at mm.bA (https://dart-hn.firebaseapp.com/main.dart.js:6702:12)
    at mM.$0 (https://dart-hn.firebaseapp.com/main.dart.js:6168:16)
    at Object.cp (https://dart-hn.firebaseapp.com/main.dart.js:1552:41)
    at D.cX (https://dart-hn.firebaseapp.com/main.dart.js:6064:3)
ORIGINAL EXCEPTION: DeferredLoadException: 'Loading main.dart.js_1.part.js failed: the code with hash 'RFPdwhA3LPHF0px4JXTX46Eyedw=' was not loaded.
event log:
 - _loadHunk: main.dart.js_1.part.js
 - download: main.dart.js_1.part.js from https://dart-hn.firebaseapp.com/main.dart.js_1.part.js
 - download success: main.dart.js_1.part.js
 - missing hunk: main.dart.js_1.part.js (RFPdwhA3LPHF0px4JXTX46Eyedw=)
```

Possibly not all the dart2js artifacts were deployed to firebase?

**Comment by matanlurey** [comment]
That's really weird. I don't see this locally, do you @leonsenft?

**Comment by matanlurey** [comment]
Ah wait, I see it now.

**Comment by matanlurey** [comment]
Ah yes, deferred loading doesn't work with `build_runner` yet.

They are working on it:
https://github.com/dart-lang/build/issues/814

**Comment by matanlurey** [comment]
This is working as of the latest version of `build_runner`:

<img width="1478" alt="screen shot 2018-03-17 at 5 18 19 pm" src="https://user-images.githubusercontent.com/168174/37561247-411755be-2a07-11e8-967b-0cb12d59c0e4.png">

For example: https://dart-hn.firebaseapp.com/item/16608827

Thanks @natebosch and @jakemac53!
